-- Archivio indipendente: nessun record preesistente in clienti viene modificato.
create table public.potenziali_clienti (
  id uuid primary key default gen_random_uuid(),
  potential_no bigint generated by default as identity unique,
  nome text not null check (length(btrim(nome)) >= 2),
  operatore text not null check (operatore in ('Francesco', 'Gisberto', 'Enzo')),
  categoria text,
  categoria_codice text,
  place_id text,
  link_recensioni text,
  link_nfc text,
  logo_data text,
  targhe integer not null default 0 check (targhe >= 0),
  carte integer not null default 0 check (carte >= 0),
  adesivi integer not null default 0 check (adesivi >= 0),
  spesa numeric(12,2) not null default 0 check (spesa >= 0),
  stato text not null default 'potenziale' check (stato in ('potenziale', 'convertito')),
  converted_client_id uuid references public.clienti(id) on delete set null,
  created_by uuid not null references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint potenziali_conversione_coerente check (
    (stato = 'potenziale' and converted_client_id is null)
    or stato = 'convertito'
  )
);

create index potenziali_clienti_active_idx on public.potenziali_clienti (potential_no desc)
  where stato = 'potenziale';
alter table public.potenziali_clienti enable row level security;

create policy potenziali_select_team on public.potenziali_clienti
  for select to authenticated using (public.is_tapnfc_operator());
create policy potenziali_insert_owner on public.potenziali_clienti
  for insert to authenticated with check (
    public.is_tapnfc_operator() and created_by = (select auth.uid())
    and stato = 'potenziale' and converted_client_id is null
    and operatore = case lower((select auth.jwt()) ->> 'email')
      when 'francesco@tapnfc.local' then 'Francesco'
      when 'gisberto@tapnfc.local' then 'Gisberto'
      when 'enzo@tapnfc.local' then 'Enzo'
      else '' end
  );
create policy potenziali_update_owner on public.potenziali_clienti
  for update to authenticated
  using (public.is_tapnfc_operator() and created_by = (select auth.uid()) and stato = 'potenziale')
  with check (public.is_tapnfc_operator() and created_by = (select auth.uid())
    and stato = 'potenziale' and converted_client_id is null
    and operatore = case lower((select auth.jwt()) ->> 'email')
      when 'francesco@tapnfc.local' then 'Francesco'
      when 'gisberto@tapnfc.local' then 'Gisberto'
      when 'enzo@tapnfc.local' then 'Enzo'
      else '' end);
create policy potenziali_delete_owner on public.potenziali_clienti
  for delete to authenticated
  using (public.is_tapnfc_operator() and created_by = (select auth.uid()) and stato = 'potenziale');

grant select, insert, update, delete on public.potenziali_clienti to authenticated;
grant usage, select on sequence public.potenziali_clienti_potential_no_seq to authenticated;

-- Una conversione equivale a un solo inserimento in clienti: i trigger esistenti
-- registrano la vendita e scalano le scorte nella stessa transazione.
create function public.converti_potenziale(
  p_id uuid, p_targhe integer, p_carte integer, p_adesivi integer, p_spesa numeric
)
returns uuid
language plpgsql security definer set search_path = ''
as $function$
declare
  prospect public.potenziali_clienti%rowtype;
  new_client_id uuid;
begin
  if (select auth.uid()) is null or not public.is_tapnfc_operator() then
    raise exception 'Operatore non autorizzato';
  end if;
  if p_targhe is null or p_carte is null or p_adesivi is null or p_spesa is null
     or p_targhe < 0 or p_carte < 0 or p_adesivi < 0 or p_spesa < 0 then
    raise exception 'Quantità o importo non validi';
  end if;

  select * into prospect from public.potenziali_clienti
    where id = p_id and created_by = (select auth.uid()) and stato = 'potenziale'
    for update;
  if not found then
    raise exception 'Potenziale non disponibile o già convertito';
  end if;
  if prospect.operatore <> case lower((select auth.jwt()) ->> 'email')
    when 'francesco@tapnfc.local' then 'Francesco'
    when 'gisberto@tapnfc.local' then 'Gisberto'
    when 'enzo@tapnfc.local' then 'Enzo'
    else '' end then
    raise exception 'Operatore del potenziale non valido';
  end if;
  if exists (
    select 1 from public.clienti c
    where lower(btrim(c.nome)) = lower(btrim(prospect.nome))
       or (nullif(btrim(prospect.link_nfc), '') is not null and c.link_nfc = prospect.link_nfc)
  ) then
    raise exception 'Cliente già presente: verifica la scheda esistente prima di convertire';
  end if;

  insert into public.clienti (
    nome, operatore, categoria, categoria_codice, place_id, link_recensioni,
    link_nfc, logo_data, targhe, carte, adesivi, spesa, stato, created_by, updated_by
  ) values (
    prospect.nome, prospect.operatore, prospect.categoria, prospect.categoria_codice,
    prospect.place_id, prospect.link_recensioni, prospect.link_nfc, prospect.logo_data,
    p_targhe, p_carte, p_adesivi, p_spesa, 'Da consegnare',
    (select auth.uid()), (select auth.uid())
  ) returning id into new_client_id;

  update public.potenziali_clienti set
    stato = 'convertito', converted_client_id = new_client_id,
    targhe = p_targhe, carte = p_carte, adesivi = p_adesivi, spesa = p_spesa,
    updated_by = (select auth.uid()), updated_at = now()
  where id = p_id;

  return new_client_id;
end;
$function$;
revoke all on function public.converti_potenziale(uuid,integer,integer,integer,numeric) from public, anon;
grant execute on function public.converti_potenziale(uuid,integer,integer,integer,numeric) to authenticated;
