plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tapreputa.tapnfc'
    compileSdk 35

    defaultConfig {
        applicationId 'com.tapreputa.tapnfc'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.0.2'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
